name: build_and_test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-node@v5
          with:
            node-version: '22.x'
        - run: npm ci
        - run: npm run testRun
